### ISSUE TITLE
Bootloop after modifying QS header count in HMD Global Android 10 ROM

### ISSUE THREAD

**Issue by antoniu200** [zacharee/Tweaker#125]
Hello,

In various ROMs for the Nokia 5.4, version 00WW_1_130 and earlier, there is a bug where the system will enter a bootloop, seemingly randomly or after a manually initated reboot. It seems the issue is due to `Binary XML file line #61 in com.android.systemui:layout/super_status_bar: Slice content://0@com.android.systemui.keyguard/main not pinned`:
<details>
> --------- beginning of crash
> 11-11 03:51:53.629  2219  2219 E AndroidRuntime: FATAL EXCEPTION: main
> 11-11 03:51:53.629  2219  2219 E AndroidRuntime: Process: com.android.systemui, PID: 2219
> 11-11 03:51:53.629  2219  2219 E AndroidRuntime: java.lang.RuntimeException: Unable to create service com.android.systemui.SystemUIService: android.view.InflateException: Binary XML file line #61 in com.android.systemui:layout/super_status_bar: Slice content://0@com.android.systemui.keyguard/main not pinned
> 11-11 03:51:53.629  2219  2219 E AndroidRuntime: 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3966)
> 11-11 03:51:53.629  2219  2219 E AndroidRuntime: 	at android.app.ActivityThread.access$1500(ActivityThread.java:220)
> 11-11 03:51:53.629  2219  2219 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1876)
> 11-11 03:51:53.629  2219  2219 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
> 11-11 03:51:53.629  2219  2219 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
> 11-11 03:51:53.629  2219  2219 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7397)
> 11-11 03:51:53.629  2219  2219 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
> 11-11 03:51:53.629  2219  2219 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
> 11-11 03:51:53.629  2219  2219 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
> 11-11 03:51:53.629  2219  2219 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #61 in com.android.systemui:layout/super_status_bar: Slice content://0@com.android.systemui.keyguard/main not pinned
> 11-11 03:51:53.629  2219  2219 E AndroidRuntime: Caused by: java.lang.IllegalStateException: Slice content://0@com.android.systemui.keyguard/main not pinned
> 11-11 03:51:53.629  2219  2219 E AndroidRuntime: 	at android.os.Parcel.createException(Parcel.java:2079)
> 11-11 03:51:53.629  2219  2219 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2039)
> 11-11 03:51:53.629  2219  2219 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1987)
> 11-11 03:51:53.629  2219  2219 E AndroidRuntime: 	at android.app.slice.ISliceManager$Stub$Proxy.getPinnedSpecs(ISliceManager.java:447)
> 11-11 03:51:53.629  2219  2219 E AndroidRuntime: 	at android.app.slice.SliceManager.getPinnedSpecs(SliceManager.java:192)
> 11-11 03:51:53.629  2219  2219 E AndroidRuntime: 	at androidx.slice.SliceManagerWrapper.getPinnedSpecs(SliceManagerWrapper.java:56)
> 11-11 03:51:53.629  2219  2219 E AndroidRuntime: 	at androidx.slice.builders.TemplateSliceBuilder.getSpecs(TemplateSliceBuilder.java:127)
> 11-11 03:51:53.629  2219  2219 E AndroidRuntime: 	at androidx.slice.builders.TemplateSliceBuilder.<init>(TemplateSliceBuilder.java:71)
> 11-11 03:51:53.629  2219  2219 E AndroidRuntime: 	at androidx.slice.builders.ListBuilder.<init>(ListBuilder.java:198)
> 11-11 03:51:53.629  2219  2219 E AndroidRuntime: 	at com.android.systemui.keyguard.KeyguardSliceProvider.onBindSlice(KeyguardSliceProvider.java:213)
> 11-11 03:51:53.629  2219  2219 E AndroidRuntime: 	at com.android.keyguard.KeyguardSliceView.refresh(KeyguardSliceView.java:399)
> 11-11 03:51:53.629  2219  2219 E AndroidRuntime: 	at com.hmdglobal.frameworks.systemui.KeyguardAssistantView.refresh(KeyguardAssistantView.java:159)
> 11-11 03:51:53.629  2219  2219 E AndroidRuntime: 	at com.android.keyguard.KeyguardStatusView.onFinishInflate(KeyguardStatusView.java:204)
> 11-11 03:51:53.629  2219  2219 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1136)
> 11-11 03:51:53.629  2219  2219 E AndroidRuntime: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
> 11-11 03:51:53.629  2219  2219 E AndroidRuntime: 	at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1263)
> 11-11 03:51:53.629  2219  2219 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1119)
> 11-11 03:51:53.629  2219  2219 E AndroidRuntime: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
> 11-11 03:51:53.629  2219  2219 E AndroidRuntime: 	at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1263)
> 11-11 03:51:53.629  2219  2219 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1119)
> 11-11 03:51:53.629  2219  2219 E AndroidRuntime: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
> 11-11 03:51:53.629  2219  2219 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:682)
> 11-11 03:51:53.629  2219  2219 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
> 11-11 03:51:53.629  2219  2219 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:481)
> 11-11 03:51:53.629  2219  2219 E AndroidRuntime: 	at com.android.systemui.statusbar.phone.StatusBar.inflateStatusBarWindow(StatusBar.java:1318)
> 11-11 03:51:53.629  2219  2219 E AndroidRuntime: 	at com.android.systemui.statusbar.phone.StatusBar.makeStatusBarView(StatusBar.java:838)
> 11-11 03:51:53.629  2219  2219 E AndroidRuntime: 	at com.android.systemui.statusbar.phone.StatusBar.createAndAddWindows(StatusBar.java:2536)
> 11-11 03:51:53.629  2219  2219 E AndroidRuntime: 	at com.android.systemui.statusbar.phone.StatusBar.start(StatusBar.java:733)
> 11-11 03:51:53.629  2219  2219 E AndroidRuntime: 	at com.android.systemui.SystemBars.createStatusBarFromConfig(SystemBars.java:73)
> 11-11 03:51:53.629  2219  2219 E AndroidRuntime: 	at com.android.systemui.SystemBars.start(SystemBars.java:39)
> 11-11 03:51:53.629  2219  2219 E AndroidRuntime: 	at com.android.systemui.SystemUIApplication.startServicesIfNeeded(SystemUIApplication.java:209)
> 11-11 03:51:53.629  2219  2219 E AndroidRuntime: 	at com.android.systemui.SystemUIApplication.startServicesIfNeeded(SystemUIApplication.java:145)
> 11-11 03:51:53.629  2219  2219 E AndroidRuntime: 	at com.android.systemui.SystemUIService.onCreate(SystemUIService.java:40)
> 11-11 03:51:53.629  2219  2219 E AndroidRuntime: 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3954)
> 11-11 03:51:53.629  2219  2219 E AndroidRuntime: 	at android.app.ActivityThread.access$1500(ActivityThread.java:220)
> 11-11 03:51:53.629  2219  2219 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1876)
> 11-11 03:51:53.629  2219  2219 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
> 11-11 03:51:53.629  2219  2219 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
> 11-11 03:51:53.629  2219  2219 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7397)
> 11-11 03:51:53.629  2219  2219 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
> 11-11 03:51:53.629  2219  2219 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
> 11-11 03:51:53.629  2219  2219 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
> 11-11 03:51:53.629  2219  2219 E AndroidRuntime: Caused by: android.os.RemoteException: Remote stack trace:
> 11-11 03:51:53.629  2219  2219 E AndroidRuntime: 	at com.android.server.slice.SliceManagerService.getPinnedSlice(SliceManagerService.java:355)
> 11-11 03:51:53.629  2219  2219 E AndroidRuntime: 	at com.android.server.slice.SliceManagerService.getPinnedSpecs(SliceManagerService.java:199)
> 11-11 03:51:53.629  2219  2219 E AndroidRuntime: 	at android.app.slice.ISliceManager$Stub.onTransact(ISliceManager.java:214)
> 11-11 03:51:53.629  2219  2219 E AndroidRuntime: 	at android.os.Binder.execTransactInternal(Binder.java:1021)
> 11-11 03:51:53.629  2219  2219 E AndroidRuntime: 	at android.os.Binder.execTransact(Binder.java:994)
> 11-11 03:51:53.629  2219  2219 E AndroidRuntime: 
> 11-11 03:51:53.631  1453  2093 W RescueParty: Noticed 1 events for UID 10137 in last 17 sec
> 11-11 03:51:53.633  2219  3024 D NetworkController.MobileSignalController(1): mccmnc value :: 22605 mConfig.show4gForLte value :: true
> 11-11 03:51:53.633  2219  3024 D NetworkController.MobileSignalController(1): Inside if condition mConfig.show4gForLte
> 11-11 03:51:53.633  2219  2219 I Process : Sending signal. PID: 2219 SIG: 9
</details>

Last night, this bootloop started happening right after I modified the QS header count, but other times I believe I did not even get to use SystemUI Tuner and the bootloop occurred.

The only fix I found is to reset data using TWRP.

I took a glance over the AOSP source code (the ROM is very close to stock), but I did not have the time to figure out exactly what causes this or how I could fix it.

Any suggestions?

**Comment by antoniu200** [comment]
I decompiled their SystemUI and saw that they forgot to close `layout/super_status_bar.xml` with the element </com.android.systemui.statusbar.phone.StatusBarWindowView>
The update where they fixed this, the phone stopped rebooting randomly.

Problem solved, issue closed.

Sorry to bother!
